import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "playwright-report/**",
      "test-results/**",
      "public/**",
      // Auto-generated by `next build` and gitignored; its triple-slash reference is Next's
      // own output, not authored code, so linting it only ever produces a false error.
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
