import type { Project } from "@/lib/types";

// All entries are demoOnly per .webby/CONTENT_TRUTH.json — sample work to communicate
// scope/quality until replaced with verified client case studies. Never render as fact.
export const projects: Project[] = [
  {
    slug: "website-noi-that-phuong-nam",
    title: "Website nội thất Phương Nam",
    category: "Website",
    summary: "Website giới thiệu sản phẩm nội thất, tối ưu tốc độ tải và chuyển đổi liên hệ.",
    demoOnly: true,
    heroAssetId: "project-cover-01",
    challenge: "Website cũ tải chậm, không tối ưu trên di động, tỉ lệ khách để lại thông tin thấp.",
    solution: "Thiết kế lại giao diện, tối ưu hình ảnh, rút gọn quy trình để lại thông tin tư vấn.",
    results: ["Tốc độ tải trang cải thiện rõ rệt", "Trải nghiệm di động mượt hơn", "Form liên hệ rút gọn còn 4 trường"],
    technology: ["Next.js", "Responsive design", "SEO on-page"],
  },
  {
    slug: "website-spa-an-nhien",
    title: "Website spa An Nhiên",
    category: "Website",
    summary: "Landing page đặt lịch dịch vụ spa với hệ thống danh mục liệu trình rõ ràng.",
    demoOnly: true,
    heroAssetId: "project-cover-02",
    challenge: "Khách hàng khó tìm đúng liệu trình phù hợp và không có kênh đặt lịch online.",
    solution: "Xây dựng danh mục dịch vụ theo nhu cầu, tích hợp form đặt lịch tư vấn.",
    results: ["Danh mục dịch vụ trực quan", "Form đặt lịch nhanh"],
    technology: ["Next.js", "Design system riêng"],
  },
  {
    slug: "website-xuat-nhap-khau-hai-au",
    title: "Website xuất nhập khẩu Hải Âu",
    category: "Website",
    summary: "Website doanh nghiệp B2B giới thiệu năng lực và ngành hàng xuất nhập khẩu.",
    demoOnly: true,
    heroAssetId: "project-cover-03",
    challenge: "Cần một kênh trình bày năng lực chuyên nghiệp cho đối tác quốc tế.",
    solution: "Thiết kế hệ thống trang giới thiệu năng lực, ngành hàng và liên hệ hợp tác.",
    results: ["Bộ nhận diện nhất quán", "Nội dung song ngữ sẵn sàng mở rộng"],
    technology: ["Next.js", "SEO đa ngôn ngữ (kế hoạch)"],
  },
  {
    slug: "website-phong-kham-tam-duc",
    title: "Website phòng khám Tâm Đức",
    category: "Website",
    summary: "Website phòng khám với lịch khám, danh mục chuyên khoa và form đặt hẹn.",
    demoOnly: true,
    heroAssetId: "project-cover-04",
    challenge: "Bệnh nhân khó tra cứu lịch khám và thông tin chuyên khoa.",
    solution: "Chuẩn hoá thông tin chuyên khoa, xây form đặt hẹn có xác nhận.",
    results: ["Thông tin chuyên khoa rõ ràng", "Form đặt hẹn có xác nhận"],
    technology: ["Next.js", "Form validation hai lớp"],
  },
  {
    slug: "website-noi-that-gia-nguyen",
    title: "Website nội thất Gia Nguyên",
    category: "Website",
    summary: "Showroom nội thất trực tuyến với bộ lọc sản phẩm theo phong cách.",
    demoOnly: true,
    heroAssetId: "project-cover-05",
    results: ["Bộ lọc sản phẩm trực quan", "Gallery tối ưu tải ảnh"],
    technology: ["Next.js", "Image optimization"],
  },
  {
    slug: "website-truong-mam-non-sao-mai",
    title: "Website trường mầm non Sao Mai",
    category: "Website",
    summary: "Website giới thiệu chương trình học và tuyển sinh cho trường mầm non.",
    demoOnly: true,
    heroAssetId: "project-cover-06",
    results: ["Trang tuyển sinh rõ quy trình", "Thư viện hoạt động trực quan"],
    technology: ["Next.js"],
  },
  {
    slug: "fanpage-quan-an-que-nha",
    title: "Fanpage quán ăn Quê Nhà",
    category: "Support MXH",
    summary: "Khắc phục sự cố tài khoản quảng cáo và tối ưu nội dung fanpage.",
    demoOnly: true,
    heroAssetId: "project-cover-07",
    challenge: "Fanpage bị hạn chế tương tác, tài khoản quảng cáo gặp lỗi thanh toán.",
    solution: "Rà soát chính sách, khắc phục lỗi tài khoản và tái cấu trúc nội dung đăng bài.",
    results: ["Tài khoản quảng cáo hoạt động ổn định trở lại", "Tần suất đăng bài đều đặn hơn"],
  },
  {
    slug: "kenh-tiktok-thoi-trang-loom",
    title: "Kênh TikTok thời trang Loom",
    category: "Support MXH",
    summary: "Tư vấn chiến lược nội dung và hỗ trợ vận hành kênh TikTok thương hiệu thời trang.",
    demoOnly: true,
    heroAssetId: "project-cover-08",
    results: ["Lịch đăng nội dung theo tuần", "Quy chuẩn kịch bản video ngắn"],
  },
  {
    slug: "kenh-youtube-review-cong-nghe",
    title: "Kênh YouTube review công nghệ",
    category: "Support MXH",
    summary: "Hỗ trợ tối ưu kênh, xử lý bản quyền và cấu trúc danh mục video.",
    demoOnly: true,
    heroAssetId: "project-cover-09",
    results: ["Kênh được cấu trúc lại theo chủ đề", "Quy trình xử lý cảnh báo bản quyền"],
  },
  {
    slug: "bo-cong-cu-so-cong-ty-viet-phat",
    title: "Bộ công cụ số công ty Việt Phát",
    category: "Dịch vụ số",
    summary: "Cung cấp và hỗ trợ bộ tài khoản Microsoft 365, Canva Pro cho đội ngũ vận hành.",
    demoOnly: true,
    heroAssetId: "project-cover-10",
    results: ["Toàn bộ nhân sự có tài khoản công cụ hợp lệ", "Hướng dẫn sử dụng rõ ràng theo phòng ban"],
  },
  {
    slug: "trien-khai-chatgpt-team-marketing",
    title: "Triển khai ChatGPT cho team marketing",
    category: "Dịch vụ số",
    summary: "Hỗ trợ đăng ký, thiết lập và hướng dẫn sử dụng ChatGPT cho đội ngũ marketing.",
    demoOnly: true,
    heroAssetId: "project-cover-11",
    results: ["Quy trình sử dụng ChatGPT theo từng vai trò", "Tài liệu hướng dẫn nội bộ"],
  },
  {
    slug: "goi-cong-cu-thiet-ke-canva-agency",
    title: "Gói công cụ thiết kế Canva cho agency nhỏ",
    category: "Dịch vụ số",
    summary: "Cung cấp gói Canva Pro và hỗ trợ thiết lập thư viện thiết kế dùng chung.",
    demoOnly: true,
    heroAssetId: "project-cover-12",
    results: ["Thư viện template dùng chung", "Quy trình duyệt thiết kế nhanh hơn"],
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}
